import React, { useEffect, useState } from 'react'
import { Pressable, ScrollView, StyleSheet, View, FlatList } from 'react-native'
import { MaterialCommunityIcons } from '@expo/vector-icons'
import * as yup from 'yup'
import { getOrderDetails, updateOrderById } from '../../api/OrderEnpoints'
import InputItem from '../../components/InputItem'
import TextRegular from '../../components/TextRegular'
import TextSemiBold from '../../components/TextSemibold'
import * as GlobalStyles from '../../styles/GlobalStyles'
import { showMessage } from 'react-native-flash-message'
import { Formik } from 'formik'
import ImageCard from '../../components/ImageCard'
import TextError from '../../components/TextError'
import { buildInitialValues } from '../Helper'
import defaultProductImage from '../../../assets/product.jpeg'
import { getDetail } from '../../api/RestaurantEndpoints'

export 